#!/bin/bash

case "$1" in
  *.dn)
    unzip -qc "$1" _files/text.md
    ;;
  *.dnote)
    unzip -qc "$1" _files/text.md
    ;;
  *.dnoted)
    cat "$1/_files/text.md"
    ;;
  *)
    echo "dnread [file]"
    ;;
esac
